### ISSUE TITLE
Any way to configure callback_path when configuring through devise ?

### ISSUE THREAD

**Issue by kofronpi** [m0n9oose/omniauth_openid_connect#15]
I would like to configure my callback URI with your gem, but I can't figure out how (or if I can). I can't seem to properly setup `callback_path` with the `openid_connect` strategy when using Devise. (see https://github.com/omniauth/omniauth/issues/593)

I'd be open to make a fork and open a PR if this not possible right now and you could give me some pointers ?

Thank you,

**Comment by m0n9oose** [comment]
Hey @kofronpi 

First of all, I have to say that I've been out of the omniauth context for a while, and it's possible that I'm missing something.

As of my understanding, you cannot do this with the "ominauth-openidconnect" gem,  because it's just an underlying provider.

Again, it's possible that I'm wrong; it's hard to say without seeing the exact code and examples of requests.

**Comment by kofronpi** [comment]
Hello @m0n9oose, thanks, I jumped at the same conclusion reading the `omniauth_openid_connect` code and ended up using the `openid_connect` gem directly to achieve what I wanted. Closing !
