### ISSUE TITLE
Confused on how to use this gem

### ISSUE THREAD

**Issue by blevine** [m0n9oose/omniauth_openid_connect#7]
Trying to hit /auth/openid_connect URL to invoke this strategy, but just get a 404.  Is this supposed to work or is there some other way to invoke this strategy?

**Comment by blevine** [comment]
Never mind.  I didn't realize that I have to redirect to auth/<name>  where <name> is the name specified in the strategy's name parameter as opposed to the name of the strategy which is 'openid_connect'.  Closing.

**Comment by hamxashahid** [comment]
Hi Blevine,

sorry to reach out directly but I think I need some help in configuring this gem with devise in my application; I am always getting `Not found. Authentication passthru.` error; 

The url that devise upon clicking 'Sign In with OpenIdConnect' goes to is: https://myapp.com/users/auth/openid_connect 

My config looks like below in `config/initializers/devise.rb` :

`config.omniauth :openid_connect, {
      name: :provider,
      scope: [:openid],
      response_type: :code,
      client_options: {
          port: 443,
          scheme: "https",
          host: "staging-oauth.provider.com",
          issuer: "https://staging-oauth.provider.com",
          authorization_endpoint: "/oauth2/auth",
          token_endpoint: "/oauth2/token",
          identifier: 'CLIENT_ID',
          secret: 'CLIENT_SECRET',
          redirect_uri: "https://myapp.com/users/auth/openid_connect/callback",
      },
  }`

I know I have added extra parameters in it but that's because I'm unsure of what exactly is required; I cant see any logs on the server as well so it means I am not hitting the correct endpoint or something

I have the following urls from provider available 
- issuer endpoint (https://staging-oauth.provider.com)
- authorization endpoint (https://staging-oauth.provider.com/oauth2/auth)
- token endpoint (https://staging-oauth.provider.com/oauth2/token)
- also I have the client id and secret

Can you please help me ?

**Comment by hamxashahid** [comment]
I figured out that `name` attribute issue i-e devise redirects to the `users/auth/openid_connect` url and name should be same as omniauth alias; but further I am getting 
`OpenIDConnect::Discovery::DiscoveryFailed` error;
